export * from './lib/color.interface';
export { formatColor } from './lib/formatting/format-color.function';
export { formatHexColor } from './lib/formatting/format-hex-color.function';
export { formatRgbColor } from './lib/formatting/format-rgb-color.function';
export { formatRgbaColor } from './lib/formatting/format-rgba-color.function';
export { applyOpacity } from './lib/manipulation/apply-opacity.function';
export { parseColor } from './lib/parsing/parse-color.function';
export { parseHexColor } from './lib/parsing/parse-hex-color.function';
export { parseRgbColor } from './lib/parsing/parse-rgb-color.function';
export { parseRgbaColor } from './lib/parsing/parse-rgba-color.function';
export { parseShortHexColor } from './lib/parsing/parse-short-hex-color.function';
