name: Publish Packages

on:
  push:
    branches:
      - main

env:
  RXJS_VERSION: 6.6.3
  ANGULAR_VERSION: 11.2.13

jobs:
  publish_packages:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Set Version Number
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: '0.0.0-PLACEHOLDER'
          replace: '0.0.${{ github.run_number }}'
          include: '.*/package.json'
      - name: Set RxJs Version
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: '0.0.0-RXJS'
          replace: '${{ env.RXJS_VERSION }}'
          include: '.*/package.json'
      - name: Set Angular Version
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: '0.0.0-ANGULAR'
          replace: '${{ env.ANGULAR_VERSION }}'
          include: '.*/package.json'
      - name: Build Packages
        run: yarn affected:build --prod --all
      - name: Test Packages
        run: yarn affected:test
      - name: Lint Packages
        run: yarn affected:lint
      - name: Prepare Publish to Github
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@raeffs'
      - name: Publish Packages to Github
        run: yarn affected --target publish --all --args="--access public --tag latest"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare Publish to NPM
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@raeffs'
      - name: Publish Packages to NPM
        run: yarn affected --target publish --all --args="--access public --tag latest"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
