name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  publish_packages:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - name: Set Version Number
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          find: '0.0.0-PLACEHOLDER'
          replace: '0.0.${{ github.run_number }}'
          include: '.*/package.json'
      - name: Build Packages
        run: yarn affected:build --prod --all
      - name: Test Packages
        run: yarn affected:test
      - name: Prepare Publish
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@raeffs'
      - name: Publish @raeffs/common
        run: yarn publish dist/packages/core/common
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @raeffs/data-source
        run: yarn publish dist/packages/data-source
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @raeffs/rxjs
        run: yarn publish dist/packages/rxjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @raeffs/color
        run: yarn publish dist/packages/core/color
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish @raeffs/testing
        run: yarn publish dist/packages/core/testing
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
